### ISSUE TITLE
how to create xsuaa instance by btp service operator

### ISSUE THREAD

**Issue by lizzzcai** [SAP/sap-btp-service-operator#102]
Hi colleagues,

is there any document or example of creating `xsuaa` instance by `btp operator` and how to pass the `xs-securty.json` as parameters?

And how to define the `runtime environment` and `scope` for my `xsuaa` broker.
 
I try the following but the status is stuck in `createInProgress`.

```yaml
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
    name: my-xsuaa-instance
spec:
    serviceOfferingName: xsuaa
    servicePlanName: broker
    parameters:
      config:
        xs-security:
          xsappname: "ai-bus-sbf-test"
          authorities:
            - $XSAPPNAME.default
          scopes:
            - name: $XSAPPNAME.default
              description: Default grant access to all endpoints exposed by ai-bus-sbf-test
```

status:
```yaml
Status:
  Conditions:
    Last Transition Time:  2021-11-09T06:38:27Z
    Message:               request POST https://service-manager.cfapps.sap.hana.ondemand.com/v1/service_instances failed: StatusCode: 503 Body: {"error":"Timeout", "description": "operation has timed out"}
    Observed Generation:   1
    Reason:                CreateInProgress
    Status:                False
    Type:                  Succeeded
    Last Transition Time:  2021-11-09T06:38:27Z
    Message:               
    Reason:                NotProvisioned
    Status:                False
    Type:                  Ready
  Observed Generation:     1
  Ready:                   False
Events:                    <none>
```

BTW is there any support channel in slack for btp operator, thanks.
