### ISSUE TITLE
Error sending request GET - Post /oauth/token: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by MichaelSp** [SAP/sap-btp-service-operator#106]
I just tried to create these resources:

#### `cloud-logging-service.yaml`
```yaml
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: my-logging-instance
spec:
  serviceOfferingName: cloud-logging
  servicePlanName: standard
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: my-logging-binding
spec:
  serviceInstanceName: my-logging-instance
  secretName: mySecret

```

But this error appears:
```yaml
conditions:
    - lastTransitionTime: '2021-11-25T20:47:23Z'
      message: >-
        Error sending request GET
        https://dev-ufn0iae5.authentication.sap.hana.ondemand.com/v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27my-logging-instance%27+and+context%2Fclusterid+eq+%274272aeda-b2c8-4472-afd9-a979e00b7e20%27+and+context%2Fnamespace+eq+%27default%27&labelQuery=_k8sname+eq+%27my-logging-instance%27:
        Get
        https://dev-ufn0iae5.authentication.sap.hana.ondemand.com/v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27my-logging-instance%27+and+context%2Fclusterid+eq+%274272aeda-b2c8-4472-afd9-a979e00b7e20%27+and+context%2Fnamespace+eq+%27default%27&labelQuery=_k8sname+eq+%27my-logging-instance%27:
        Post /oauth/token: unsupported protocol scheme ""
      observedGeneration: 1
      reason: InProgress
      status: 'False'
      type: Succeeded
    - lastTransitionTime: '2021-11-25T20:47:23Z'
      message: ''
      reason: NotProvisioned
      status: 'False'
      type: Ready

```

Anything I'm doing wrong on my end?

---- 
More context for debugging

### `kustomization.yaml`
```yaml

resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
  - namespace.yaml
  - cloud-logging-service.yaml

helmCharts:
  - name: sap-btp-operator
    repo: https://sap.github.io/sap-btp-service-operator
    version: v0.1.18
    releaseName: sap-btp-operator
    namespace: sap-btp-system
    includeCRDs: true
    valuesFile: sap-btp-values.yaml
```

#### `sap-btp-values.yaml`
```yaml

manager:
  secret:
    clientid: XXX
    clientsecret: XXX
    url: https://dev-ufn0iae5.authentication.sap.hana.ondemand.com
    xsappname: XXX
    sm_url: https://service-manager.cfapps.sap.hana.ondemand.com
```
