### ISSUE TITLE
Question: pairing second K8s cluster to the same instance of 'cloud logging Service' fails

### ISSUE THREAD

**Issue by i035249** [SAP/sap-btp-service-operator#144]
Question:

We installed one service instance of 'cloud logging Service' in our account in CF with quota = 1.
When installed successfully the service instance to the first K8s cluster with the following yaml:
```
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: "logging-large"
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
spec:
  serviceOfferingName: "cloud-logging"
  servicePlanName: "large"

```

On attempt to pair the second cluster with the same configuration file it failed with the following error message:
    _With error: Status: 403; ErrorMessage: Forbidden; Description: Quota is not sufficient for this request; ResponseError: \u003cnil\u003e"?_

Is this the desire behavior / bug ?
Kindly advice.

regards,
Yoram Yair
Developer @ SAP
