### ISSUE TITLE
missing digest option on btp-operator chart

### ISSUE THREAD

**Issue by mordabi** [SAP/sap-btp-service-operator#170]
Hi,
 I'm trying to use digest on the sapbtp-operator images
in the deployment file there are two images the operator uses, the core image of sap operator that is expose and his version can be change via the `tag` value but not with digest (sha256) ,and `quay.io/brancz/kube-rbac-proxy:v0.11.0 ` image that is hardcoded to the deployment file, hence I can't change his version (not exposed as a value)

chart current values file no digest/sha option :
```yaml
image:
    repository: ghcr.io/sap/sap-btp-service-operator/controller
    tag: master
```
chart - template/deployment.yaml file (kube-rbac-proxy img is hardcoded): 
```yaml
 containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: quay.io/brancz/kube-rbac-proxy:v0.11.0 #hardcoded 
```
I suggest to expose kube-rbac-proxy as value (tag,repo, sha, etc..) and add the `sha` option for both images on the deployment file
