### ISSUE TITLE
Credential Rotation feature stuck in "CredRotationInProgress" with "unsupported protocol scheme" message

### ISSUE THREAD

**Issue by levinanton** [SAP/sap-btp-service-operator#185]
### Context

Trying to apply "credentials rotation" feature https://github.com/SAP/sap-btp-service-operator#credentials-rotation for the existing `ServiceBinding`.

SAP BTP Service Operator version: `0.2.7`

Service Binding:

```yaml
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: ****
  namespace: ****
spec:
  serviceInstanceName: ****
  parameters:
    credential-type: X509_GENERATED
  credentialsRotationPolicy:
    enabled: true
    rotationFrequency: '5m'
    rotatedBindingTTL: '1m'
```

### Issue

Service Binding (and underlying `Secret`) are not rotated.

### Status

```
Status:
  Binding ID:  bc782b64-6c89-4ac0-9ea9-b393135f64c1
  Conditions:
    Last Transition Time:  2022-07-18T07:01:43Z
    Message:               ServiceBinding provisioned successfully
    Observed Generation:   1
    Reason:                Created
    Status:                True
    Type:                  Succeeded
    Last Transition Time:  2022-07-18T07:01:43Z
    Message:               
    Reason:                Provisioned
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-07-23T19:12:10Z
    Message:               Patch /v1/service_bindings/bc782b64-6c89-4ac0-9ea9-b393135f64c1: unsupported protocol scheme ""
    Observed Generation:   2
    Reason:                Preparing
    Status:                True
    Type:                  CredRotationInProgress
  Instance ID:             d38b79c9-ddfd-4a26-b2f9-d49e2a5c0fe5
  Observed Generation:     1
  Ready:                   True
```

### Question

What would latest status message mean?

```
Patch /v1/service_bindings/bc782b64-6c89-4ac0-9ea9-b393135f64c1: unsupported protocol scheme ""
```
