### ISSUE TITLE
credentialsRotationPolicy not rotate automatically after create a new service binding with credentialsRotationPolicy config

### ISSUE THREAD

**Issue by ekko100120** [SAP/sap-btp-service-operator#197]
hello, guys,

   I have create a service binding by `kubectl` with below config, but i found the service binding  and secret not rotate automatically follow by `rotationFrequency`, is there  a detail Operation mechanism description that this CRD work on , or is there an example config for `credentialsRotationPolicy` feature?

```yaml
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: abc-cornerstone-btp-credstore
  namespace: dfs
spec:
  serviceInstanceName: btp-credstore-instance
  credentialsRotationPolicy:
    enabled: true
    rotationFrequency: 2m
#    rotatedBindingTTL:
```
