### ISSUE TITLE
Consuming secret values as environment variables using templates

### ISSUE THREAD

**Issue by LenaHoinkis** [SAP/sap-btp-service-operator#202]
# Problem

We like to consume secret key/value pairs of the secrets created by the BTPServiceOperator as environment variables for our containers (See [k8s docu](https://kubernetes.io/docs/concepts/configuration/secret/#use-cases)). The current format of the secrets does not allow this:
```
...
data:
  instance_guid: xxx==
  instance_name: xxx==
  label: Y2ljZC1nZWFyLWQwNzEyODMtZGV2
  plan: ZGVmYXVsdA==
  servicekey.json: servicekey //Base64string
```

We could only use the servicekey directly. But our consumers are opensource projects (e.g. [elasticsearch-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter)) which do not know the serviceKey json string and how it looks like, they need specific key/values.

## Example

The container we use requires the environment variable `$OPENSEARCH_USER` to load it into the configuration.

The `servicekey` containing the value has this format:
```
{
  "description": "AWS OpenSearch",
  "username": "username1"
}
```

To load it with ` envFrom: - secretRef: ` the secret should look like this:
```
apiVersion: v1
kind: Secret
stringData:
  OPENSEARCH_USER: username1 //Base64string
```

# Proposed Solution 
We think of a solution where we can specify how the secrets BTPServiceOperator creates should look like. It will take a Go Template to create the secret in the desired format. 
The template could be defined directly in the service binding like here in the field `secretTemplate`:

```
  apiVersion: services.cloud.sap.com/v1
  kind: ServiceBinding
  metadata:
      namespace: ns
      name: x
  spec:
      serviceInstanceName: x
      externalName: y
      secretTemplate: |-
        apiVersion: services.cloud.sap.com/v1
        kind: Secret
        name: opensearch_user
        stringData:
            OPENSEARCH_USER: {{ .serviceKey.username }}
```

In the end the BTPServiceOperator will use `secretTemplate` to generate the secret.
With Go Template it should be easy to replace the `.serviceKey.username` with the value giving in the servicekey.

# Alternatives / Workarounds

We have also thought of 2 alternative approaches to get it running without changing the BTPServiceOperator
- implement and deploy some kind of an adapter component which modifies the secrets
- (fork and) modify the helm charts and implement an unclean mapping solution directly.

But having the functionality here centrally in the BTPServiceOperator will make it a lot easier for the users and will save development effort for many teams using this solution.
