### ISSUE TITLE
Feature Request to apply annotation in secret.

### ISSUE THREAD

**Issue by Mahi1704** [SAP/sap-btp-service-operator#211]
1. We use flagger for our release management. Flagger creates the blue green deployment, this also means that secrets are also created for both the deployments with some suffixes, however this can be avoided with certain annotations. 
2. We our supplied annotations to be applied to secrets created when the service bindings are created, this does not happen right now and we have to add annotation to the secret manually.
3. Service binding YAML -
```
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
    name: btp-operator-oct
    namespace: family-mdcs-dev
    annotations:
      flagger.app/config-tracking: disabled
spec:
    serviceInstanceName: btp-operator-oct
    parameters:
      credential-type: X509_GENERATED
    credentialsRotationPolicy:
      enabled: true
      rotationFrequency: "10m"
      rotatedBindingTTL: "5m" 
```

4. We want a way to supply this annotation so that flagger doesn't create a copy of it -
```
 annotations:
      flagger.app/config-tracking: disabled
```
