### ISSUE TITLE
Error when creating instances/bindings with latest operator version

### ISSUE THREAD

**Issue by tomfrenken** [SAP/sap-btp-service-operator#222]
Hey team,

when creating the following service instance:

```
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
    name: operator-connectivity-service
spec:
    serviceOfferingName: connectivity
    servicePlanName: connectivity_proxy
```

I receive the following error:

```
Message:               Error sending request GET /v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27operator-destination-service%27+and+context%2Fclusterid+eq+%27e0637764-aa32-4475-be85-03e6c67845bc%27+and+context%2Fnamespace+eq+%27default%27&labelQuery=_k8sname+eq+%27operator-destination-service%27: Get "/v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27operator-destination-service%27+and+context%2Fclusterid+eq+%27e0637764-aa32-4475-be85-03e6c67845bc%27+and+context%2Fnamespace+eq+%27default%27&labelQuery=_k8sname+eq+%27operator-destination-service%27": unsupported protocol scheme ""
```

Can you tell me if I did anything wrong or if this is a bug of the operator?

Operator Version: 0.3.0 (also tried 0.2.9 and previously used 0.1.9)
Kubernetes Version: 1.24.7
Cluster: Gardener Managed / GCP
Helm Version: 3.10.1
