### ISSUE TITLE
bindings rotation parameters clarification needed

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#224]
I have tried out the binding rotation as described here: https://github.com/SAP/sap-btp-service-operator#credentials-rotation

I applied to the following `spec` parameters in the original `xsuaa-oidc-x509-binding` binding definition and updated the binding.

```
spec:
  credentialsRotationPolicy:
    enabled: true
    rotatedBindingTTL: 30s
    rotationFrequency: 300s
  externalName: xsuaa-oidc-x509-binding
```
The `xsuaa-oidc-x509-binding` binding went into **Rotate** state and as a result a new binding got created.

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/52403733/201887807-778a8d80-c89d-4830-966f-0f49c3dc1519.png">

However this is not what I would expect: I wanted to keep rotating my credentials every 5 minutes (==300seconds) with the TTL duration for the bindings exchange of 30 seconds. 
Still  it looks like the credentials are being rotated. The value `lastCredentialsRotationTime: '2022-11-15T03:13:13Z'` is the timestamp of the last rotation around 6 hours ago. Does it mean there are some minimal values **rotationFrequency** and **rotatedBindingTTL** must abide by ? 
Can you help explain ?
