### ISSUE TITLE
Need help to create x509 binding

### ISSUE THREAD

**Issue by saiharish** [SAP/sap-btp-service-operator#231]
Hello Colleagues,

We evaluating btp-operator and in the process trying to create x509 based binding for Destination service. 

Below is my yaml to create the service 

```
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: test-destination2
spec:
  serviceOfferingName: destination
  servicePlanName: lite
  externalName: test-destination-config
  parameters:
    credential-type: X509_GENERATED
```
    
Below is my yaml to create the binding

```
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
    name: destination-binding-mtls
spec:
    serviceInstanceName: test-destination2
    externalName: destination-binding-mtls
    secretName: destination-binding-mtls
```

The creation of the service and the binding is successful but the secret that gets created is having the credential-type as binding-secret and not x509. Could you please help what am I doing wrong here ?
