### ISSUE TITLE
How to make a helm chart deployment know to un-deploy the temp secret bindings ?

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#246]
How to make a helm chart deployment know to un-deploy the temp secret bindings ?

Reference: https://github.com/SAP/sap-btp-service-operator/issues/224

Based on the above [discussion](https://github.com/SAP/sap-btp-service-operator/issues/224) there is one remaining **caveat** that the initial helm chart deployment is not aware of the temporary x509 secret bindings that might get created according to the rotation policy. 

Thus if a chart is getting un-deployed it will not remove these additional temp secret bindings. 
That will result in the un-deployment being incomplete as a given service instance or instances cannot be disposed off until all of their bindings are gone. 

Ideally the btp-service-operator reconciler is run every time a chart is getting un-deployed ? What do you reckon?

**Comment by kerenlahav** [comment]
Hi Piotr,
Do you have a log of such a case?
when you undeploy a chart all resources should be deleted, the temp secret is bound to a serviceBinding, when you undeploy a chart the serviceBinding is deleted and this will delete the secret as well

**Comment by ptesny** [comment]
Hi Keren, I can reproduce it at will...
here you go....

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/52403733/214031362-9dec4148-bb99-487d-9c9c-76a74545145d.png">


<img width="1646" alt="image" src="https://user-images.githubusercontent.com/52403733/214031252-3a57e70c-0ae6-4329-95be-e51dd16e6984.png">

Let me forceRotate the xsuaa x509 binding....

```
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  annotations:
    meta.helm.sh/release-name: app1-app
    meta.helm.sh/release-namespace: approuter
    services.cloud.sap.com/forceRotate: ''
  creationTimestamp: '2023-01-23T10:01:30Z'
  finalizers:
    - services.cloud.sap.com/sap-btp-finalizer
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: xsuaa-approuter-x509-binding
```
You can see below the temp xsuaa x509 service binding got created as depicted below:

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/52403733/214031929-47ef1ae4-0786-4b5f-9fa3-0f517938713c.png">

now let me un-deploy the chart:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/52403733/214032165-0b4e24ec-204d-4136-93e9-7eaf09e0416a.png">

the chart is gone
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/52403733/214032414-47a2e540-87a0-4194-914e-690692015f9f.png">

The temp binding is not gone: 
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/52403733/214032542-6d99972c-5720-4a31-ad38-d7c46d398d5a.png">

and the service instance could not be deleted as follows:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/52403733/214032701-5b935349-cefd-4b2f-b14a-6e92d1f172d0.png">

I hope that helps;

PS. If I delete manually the temp binding the service instance will be eventually gone after some time
