### ISSUE TITLE
Create Applications using btp-operator

### ISSUE THREAD

**Issue by yemramirezca** [SAP/sap-btp-service-operator#261]
Hi colleagues,
When I try to create "Application" for Integration Suite from the BTP cockpit I get the following options as seen in the screenshots.  This approach works, however we want to avoid manual work and do it programatically using the k8s sap-btp-operator.
So I tried to create the k8s resource as the yaml below...

```yaml
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: "integration-suite"
spec:
  serviceOfferingName: it-acfun001-prov
  servicePlanName: enterprise_agreement

```

However it fails due to "ServiceInstance create failed: couldn't find the service offering 'it-acfun001-prov'"
Is it possible to create this "Applications" that we see from the btp-cockpit using the sap-btp-operator at all? Thanks for any hint in advance :)

![Screenshot 2023-03-07 at 18 33 29](https://user-images.githubusercontent.com/8931451/223504309-6d2430e0-e4eb-4746-89d5-0cfbb3d0e06f.png)
![Screenshot 2023-03-07 at 18 34 29](https://user-images.githubusercontent.com/8931451/223504313-12dcc639-cbac-4281-97de-ceaef62c9d84.png)
