### ISSUE TITLE
Kyverno required PodDisruptionBudgets

### ISSUE THREAD

**Issue by T-002** [SAP/sap-btp-service-operator#262]
As part of our kyverno policies, PodDisruptionBudgets need to be defined to allow the installation of the BTP Operator into our clusters.

*Proposed Fix*
* Add PDB definition to the installation in case KubernetesMatchLabels are enabled
* Add some documentation to the default values.yaml

`kubectl get polr cpol-require-pdb -n sap-btp-operator -o jsonpath='{.results[?(@.result=="fail")]}' | yq -p json -`

```
category: Sample
message: There is no corresponding PodDisruptionBudget found for this Deployment.
policy: require-pdb
resources:
  - apiVersion: apps/v1
    kind: Deployment
    name: sap-btp-operator-controller-manager
    namespace: sap-btp-operator
    uid: [...]
result: fail
rule: require-pdb
scored: true
source: kyverno
timestamp:
  [...]
```

**Comment by T-002** [comment]
sapbtp-operator-charts/templates/pdb.yml
```
{{- if eq .Values.manager.kubernetesMatchLabels.enabled true }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: btp-operator-manager-pdb
  namespace: {{.Release.Namespace}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sap-btp-operator
      app.kubernetes.io/name: sap-btp-operator
{{- end }}
```
