### ISSUE TITLE
Security Context not rendered correctly

### ISSUE THREAD

**Issue by T-002** [SAP/sap-btp-service-operator#264]
https://github.com/SAP/sap-btp-service-operator/blob/a3f26b9759be93db89656af4e64b5f76c3168179/sapbtp-operator-charts/templates/deployment.yml#L52
https://github.com/SAP/sap-btp-service-operator/blob/a3f26b9759be93db89656af4e64b5f76c3168179/sapbtp-operator-charts/templates/deployment.yml#L93

The following line does not render correctly, in case the following security context might be added:
```
    securityContext:
      capabilities:
        drop:
          - all
      runAsNonRoot: true
```

A patch could look as follows:
```          {{- toYaml .Values.manager.securityContext | nindent 12 }}```
