### ISSUE TITLE
Secret credentials has an incorrect `instance_name` (when externalName is used)

### ISSUE THREAD

**Issue by pvnn** [SAP/sap-btp-service-operator#270]
Hi colleagues,

**We face an issue when creating a `ServiceInstance` with `externalName`, which according to the documentaton is the name for the service instance in SAP BTP and is what applications want to actually consume in their apps.**

**Steps to repoduce:**

1. Create a service instance as shown below:
``` yaml
    apiVersion: services.cloud.sap.com/v1
    kind: ServiceInstance
    metadata:
        name: my-service-instance
    spec:
        serviceOfferingName: sample-service
        servicePlanName: sample-plan
        externalName: my-service-instance-external
        parameters:
          key1: val1
          key2: val2
```

2. Create a service binding:
``` yaml
  apiVersion: services.cloud.sap.com/v1
  kind: ServiceBinding
  metadata:
      name: my-binding
  spec:
      serviceInstanceName: my-service-instance
      externalName: my-binding-external
      secretName: mySecret
      parameters:
        key1: val1
        key2: val2      
```
3. Check the secret details in the k8s cluster where this is executed.
```
kubectl get secrets mySecret
```
 
**Issue:**
The secret metadata always contains the instance name as the k8s service instance name. **This is incorrect when an externalName is specified as the consumers (apps) expect to consume this e.g. via [@sap/xsenv](https://www.npmjs.com/package/@sap/xsenv) using instance name from BTP (e.g. as present in the service catalog)**

```
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: mySecret
stringData:
  type: sample-service
  provider: SAP
  instance_guid: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  instance_name: my-service-instance # This should be my-service-instance-external
  ...
```

Issue seems to be in the [service binding controller code here](https://github.com/SAP/sap-btp-service-operator/blob/main/controllers/servicebinding_controller.go#L702)
IMO updating this to use externalName from instance (when it exists should solve the issue).

Please take over and provide a fix for this.

Thanks & Regards,
Pavan
