### ISSUE TITLE
ClientSecret is not changed after credential rotation

### ISSUE THREAD

**Issue by jay001199** [SAP/sap-btp-service-operator#275]
Our clientsecret is not in the root directory of secret, but in uaa.clientSecret. In this case, there is no change in clientsecret after the credential rotation.
As shown in the figure below, we get the latest secret compared with TTL's secret. In fact, the content is exactly the same.
![image](https://user-images.githubusercontent.com/32971954/228500252-77abe095-7a5a-4c00-9f0c-4d0b918b4198.png)
below is our servicebinding config
```
spec:
  credentialsRotationPolicy:
    enabled: true
    rotatedBindingTTL: 1h
    rotationFrequency: 300s
  externalName: dpi
  secretName: dpi
  serviceInstanceName: dpi
```
