### ISSUE TITLE
Unable to create a service instance: 'CreateInProgress' status stays forever

### ISSUE THREAD

**Issue by dfwonkey** [SAP/sap-btp-service-operator#305]
__Description__

Hi,

I am following the documentation to create a service instance(on an AWS environment) through the sap-btp-operator(latest version):
https://github.com/SAP/sap-btp-service-operator#using-the-sap-btp-service-operator

with the example of the deployment that uses the default access credentials type:
```
helm upgrade --install <release-name> sap-btp-operator/sap-btp-operator \
    --create-namespace \
    --namespace=sap-btp-operator \
    --set manager.secret.clientid=<clientid> \
    --set manager.secret.clientsecret=<clientsecret> \
    --set manager.secret.sm_url=<sm_url> \
    --set manager.secret.tokenurl=<url>
```

The creation of the service instance never ends.
Here is the relevant describe log:

```
$ kubectl describe serviceinstance alogs
```
```yml
Name:         alogs
Namespace:    sap-btp-operator
Labels:       <none>
Annotations:  <none>
API Version:  services.cloud.sap.com/v1
Kind:         ServiceInstance
Metadata:
  Creation Timestamp:  2023-07-18T08:27:51Z
  Finalizers:
    services.cloud.sap.com/sap-btp-finalizer
  Generation:  1
  Managed Fields:
    API Version:  services.cloud.sap.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"services.cloud.sap.com/sap-btp-finalizer":
    Manager:      Go-http-client
    Operation:    Update
    Time:         2023-07-18T08:27:51Z
    API Version:  services.cloud.sap.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:ready:
    Manager:      Go-http-client
    Operation:    Update
    Subresource:  status
    Time:         2023-07-18T08:27:51Z
    API Version:  services.cloud.sap.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:serviceOfferingName:
        f:servicePlanName:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2023-07-18T08:27:51Z
  Resource Version:  41692905
  UID:               24c62537-d491-4999-b95b-7c50b31488fb
Spec:
  External Name:          alogs
  Service Offering Name:  application-logs
  Service Plan Name:      lite
  User Info:
    Groups:
      system:masters
      system:authenticated
    UID:       system:cluster-admin
    Username:  system:cluster-admin
Status:
  Conditions:
    Last Transition Time:  2023-07-18T08:27:51Z
    Message:               Pending
    Observed Generation:   1
    Reason:                CreateInProgress
    Status:                False
    Type:                  Succeeded
    Last Transition Time:  2023-07-18T08:27:51Z
    Message:
    Observed Generation:   1
    Reason:                NotProvisioned
    Status:                False
    Type:                  Ready
  Ready:                   False
Events:                    <none>
```
__Expected result__

The serviceinstance should be Ready

__Actual result__

The serviceinstance is in Status: `CreateInProgress` forever

__Steps to reproduce__

See above
