### ISSUE TITLE
v0.5.3 wants to post an update to all existing ServiceInstances which fails on Audit Log

### ISSUE THREAD

**Issue by pre** [SAP/sap-btp-service-operator#358]
We updated from v0.3.6 -> v0.5.3 

We don't have any special local configuration for the sap-btp-service-operator.

The updated controller wants to post an `update` api call to all  existing BTP `ServiceInstances`. This worked on all other services except Audit Log which fails with 

```
status:
  conditions:
  - lastTransitionTime: "2023-10-20T10:49:39Z"
    message: 'ServiceInstance update failed: Status: 400; ErrorMessage: <nil>; Description:
      Updating service is currently not supported operation. Please create a new service
      with the desired updates and bind to it; ResponseError: <nil>'
    observedGeneration: 1
    reason: UpdateFailed
    status: "False"
    type: Succeeded
  - lastTransitionTime: "2022-08-25T07:41:29Z"
    message: ""
    observedGeneration: 1
    reason: Provisioned
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-10-20T10:49:39Z"
    message: 'ServiceInstance update failed: Status: 400; ErrorMessage: <nil>; Description:
      Updating service is currently not supported operation. Please create a new service
      with the desired updates and bind to it; ResponseError: <nil>'
    observedGeneration: 1
    reason: UpdateFailed
    status: "True"
    type: Failed
  hashedSpec: e633c12d7a499d2d935eba9cbf5e9d48
  instanceID: 6cd0e6a4-f3ef-4f5b-9600-bee1c96bfb14
  observedGeneration: 1
  ready: "True"
  tags:
  - auditlog
  - audit log
  - cf
```

We did not incorporate any changes to these existing `ServiceInstance` resources prior to updating the sap-btp-service-operator. 

However,  I can also see from BTP that almost every other service there owned by the btp operator has the Changed On day as today.

Any ideas what could be causing this? We're hesitant to pushing the update to non-development environments (we have many) until we've figured out a way to not get the Audit Log ServiceInstance in `UpdateFailed` state in each environment.
