### ISSUE TITLE
Caching All Secrets - Followup

### ISSUE THREAD

**Issue by ralikio** [SAP/sap-btp-service-operator#440]
I Created a service instance and a binding for version 0.6.3. After upgrade to 0.6.4 label `managed-by` has not been added. The solution proposed in https://github.com/SAP/sap-btp-service-operator/issues/432 is not acceptable because it misses old secrets update. You should be able to reconcile correct secrets  because there is a reference to them stored in a binding. For example, there is `spec.secretName` in my binding and the secret itself contains `ownerReference`:
```
  ownerReferences:
    - apiVersion: services.cloud.sap.com/v1
      kind: ServiceBinding
      name: test
      uid: cc992891-cbd0-4da9-bb0a-1713f89399a9
      controller: true
      blockOwnerDeletion: true
```
