### ISSUE TITLE
SAP BTP Operator credential rotation leaves many "backup" service-bindings in state CreateInProgress

### ISSUE THREAD

**Issue by BarzanaPanajotova** [SAP/sap-btp-service-operator#467]
We have configured service binding rotation as described here: https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#service-binding-rotation .

As far as I understand the service-binding stays with the same name and when the rotation occurs, the old binding is backed up with a name like <binding name>-hjs3d . This binding should be successfully created and deleted when the `rotatedBindingTTL` is passed. In our case however the new "backup" binding is not cleared in the specified timeframe (even after invoking `services.cloud.sap.com/forceRotate: "true" `.

For example:
```
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: test-binding
  namespace: test-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceInstanceName: test-binding
  secretName: test-secret
  parameters:
    credential-type: X509_GENERATED
    key-length: 4096
    validity: 14
    validity-type: DAYS
    app-identifier: test-id
  credentialsRotationPolicy:
    enabled: true
    rotatedBindingTTL: 5m
    rotationFrequency: 1h
```
and the status on the clusters is:

NAMESPACE NAME INSTANCE STATUS READY MESSAGE
│ test-namespace test-binding test-binding Created True ServiceBinding provisioned s │
│ test-namespace test-binding-3jm0sw test-binding CreateInProgress False binding with same name exist │
│ test-namespace test-binding-eyqvea test-binding CreateInProgress False binding with same name exist │

Why is the backup is stuck in CreateInProgress and the "errored" bindings are not cleared after the ttl is passed?
How should we proceed with this issue? It has happened on all our clusters.

We use ArgoCD for deployment of the helm charts if it matters.
Image:     sap-btp-service-operator/controller:v0.6.8
