### ISSUE TITLE
Missing CRDs in helm chart?

### ISSUE THREAD

**Issue by tomfrenken** [SAP/sap-btp-service-operator#60]
Hello operator team,

I was trying to use the operator, but after installing the helm chart (with no errors) and applying the following yaml:

```
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
    name: operator-destination-service
spec:
    serviceOfferingName: destination
    servicePlanName: lite
```

I receive the following error when reading the logs of the service:

```
error: no kind "ServiceInstance" is registered for version "services.cloud.sap.com/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

I believed I followed all the steps mentioned in the setup, what am I missing?
